version: 3.8;
services:
  db:
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
    pull_policy: always
    command: start --log trace --user root --pass root
  api:
    image: rust:latest
    ports:
      - 4000:4000
    volumes:
      - .:/app
    command: bash -c "cargo install cargo-watch && cd /app && cargo watch --exec run"
  # docker run --rm --pull always -p 8000:8000 surrealdb/surrealdb:latest start
